package main

/*
Simple Example: Basic usage of goseekdb with Embedding Functions

This example demonstrates the most common operations with embedding functions:
1. Create a client connection
2. Create a collection with embedding function
3. Add data using documents (embeddings auto-generated)
4. Query using query texts (embeddings auto-generated)
5. Print query results

This is a minimal example to get you started quickly with embedding functions.
*/

import (
	"context"
	"fmt"
	"log"

	"github.com/ob-labs/seekdb-go"
)

func main() {
	ctx := context.Background()

	// ==================== Step 1: Create Client Connection ====================
	// You can use embedded mode, server mode, or OceanBase mode
	// For this example, we'll use server mode (you can change to embedded or OceanBase)

	// Embedded mode (local seekdb) - Not yet implemented, requires CGo
	// client, err := goseekdb.NewClient(
	//     goseekdb.WithPath("./seekdb.db"),
	//     goseekdb.WithDatabase("test"),
	// )

	// Server mode (connecting to remote seekdb server)
	client, err := goseekdb.NewClient(
		goseekdb.WithHost("127.0.0.1"),
		goseekdb.WithPort(2881),
		goseekdb.WithDatabase("test"),
		goseekdb.WithUser("root"),
		goseekdb.WithPassword(""),
	)
	if err != nil {
		log.Fatalf("Failed to create client: %v", err)
	}
	defer client.Close()

	// OceanBase mode (remote OceanBase server)
	// client, err := goseekdb.NewClient(
	//     goseekdb.WithHost("127.0.0.1"),
	//     goseekdb.WithPort(2881),
	//     goseekdb.WithTenant("test"),  // OceanBase default tenant
	//     goseekdb.WithDatabase("test"),
	//     goseekdb.WithUser("root"),
	//     goseekdb.WithPassword(""),
	// )

	// ==================== Step 2: Create a Collection with Embedding Function ====================
	// A collection is like a table that stores documents with vector embeddings
	collectionName := "my_simple_collection"

	// Create collection with default embedding function
	// The embedding function will automatically convert documents to embeddings
	// Note: This requires ONNX Runtime to be installed. If not available,
	// you can provide pre-computed embeddings or use a custom embedding function.
	collection, err := client.CreateCollection(ctx, collectionName)
	// The default ONNX embedding function will be used automatically if available
	if err != nil {
		log.Fatalf("Failed to create collection: %v", err)
	}

	fmt.Printf("Created collection '%s' with dimension: %d\n", collectionName, collection.Dimension())
	fmt.Printf("Distance metric: %s\n", collection.Distance())

	// ==================== Step 3: Add Data to Collection ====================
	// With embedding function, you can add documents directly without providing embeddings
	// The embedding function will automatically generate embeddings from documents

	documents := []string{
		"Machine learning is a subset of artificial intelligence",
		"Python is a popular programming language",
		"Vector databases enable semantic search",
		"Neural networks are inspired by the human brain",
		"Natural language processing helps computers understand text",
	}

	ids := []string{"id1", "id2", "id3", "id4", "id5"}

	metadatas := []goseekdb.Metadata{
		{"category": "AI", "index": 0},
		{"category": "Programming", "index": 1},
		{"category": "Database", "index": 2},
		{"category": "AI", "index": 3},
		{"category": "NLP", "index": 4},
	}

	// Add data with documents only - embeddings will be auto-generated by embedding function
	err = collection.Add(ctx, ids, documents,
		goseekdb.WithMetadatas(metadatas),
		// Note: No need to provide embeddings - they're automatically generated
	)
	if err != nil {
		log.Fatalf("Failed to add documents: %v", err)
	}

	fmt.Printf("\nAdded %d documents to collection\n", len(documents))
	fmt.Println("Note: Embeddings were automatically generated from documents using the embedding function")

	// ==================== Step 4: Query the Collection ====================
	// With embedding function, you can query using text directly
	// The embedding function will automatically convert query text to query vector

	// Query using text - query vector will be auto-generated by embedding function
	queryText := "artificial intelligence and machine learning"

	results, err := collection.Query(ctx,
		[]string{queryText}, // Query text - will be embedded automatically
		3,                   // Return top 3 most similar documents
	)
	if err != nil {
		log.Fatalf("Failed to query: %v", err)
	}

	fmt.Printf("\nQuery: '%s'\n", queryText)
	if len(results.IDs) > 0 {
		fmt.Printf("Query results: %d items found\n", len(results.IDs[0]))
	}

	// ==================== Step 5: Print Query Results ====================
	if len(results.IDs) > 0 {
		for i := 0; i < len(results.IDs[0]); i++ {
			fmt.Printf("\nResult %d:\n", i+1)
			fmt.Printf("  ID: %s\n", results.IDs[0][i])
			fmt.Printf("  Distance: %.4f\n", results.Distances[0][i])

			if results.Documents != nil && len(results.Documents[0]) > i {
				fmt.Printf("  Document: %s\n", results.Documents[0][i])
			}

			if results.Metadatas != nil && len(results.Metadatas[0]) > i {
				fmt.Printf("  Metadata: %+v\n", results.Metadatas[0][i])
			}
		}
	}

	// ==================== Step 6: Cleanup ====================
	// Delete the collection
	err = client.DeleteCollection(ctx, collectionName)
	if err != nil {
		log.Fatalf("Failed to delete collection: %v", err)
	}

	fmt.Printf("\nDeleted collection '%s'\n", collectionName)
	fmt.Println("\nSimple example completed successfully!")
}
